shader_set(sh_wavewarp_anchor);
var tex = sprite_get_texture(sprite_index, image_index);
var uvs = sprite_get_uvs(sprite_index, image_index);
shader_set_uniform_f(shader_get_uniform(sh_wavewarp_anchor, "u_time"), current_time / 1000);
shader_set_uniform_f(shader_get_uniform(sh_wavewarp_anchor, "u_amplitude"), 0.001);
shader_set_uniform_f(shader_get_uniform(sh_wavewarp_anchor, "u_frequency"), 300);
shader_set_uniform_f(shader_get_uniform(sh_wavewarp_anchor, "u_speed"), 0.5);
shader_set_uniform_f(shader_get_uniform(sh_wavewarp_anchor, "u_rainbow_speed"), 0);
shader_set_uniform_f(shader_get_uniform(sh_wavewarp_anchor, "u_saturation"), 1);
shader_set_uniform_f(shader_get_uniform(sh_wavewarp_anchor, "u_uv_top_left"), uvs[0], uvs[1]);
shader_set_uniform_f(shader_get_uniform(sh_wavewarp_anchor, "u_uv_bottom_right"), uvs[2], uvs[3]);
var anchor_screen_y = 376;
var uv_anchor_y = lerp(uvs[1], uvs[3], 1);
shader_set_uniform_f(shader_get_uniform(sh_wavewarp_anchor, "u_anchor_y"), uv_anchor_y);
texture_set_stage(0, tex);
shader_set_uniform_i(shader_get_uniform(sh_wavewarp_anchor, "u_texture"), 0);
shader_set_uniform_f(shader_get_uniform(sh_wavewarp_anchor, "u_flat_color_mode"), 0.45);
var purpleoverlay = 1376277;
texture_set_stage(0, tex);
shader_set_uniform_i(shader_get_uniform(sh_wavewarp_anchor, "u_texture"), 0);
draw_sprite_ext(sprite_index, image_index, x, y + 72, image_xscale, image_yscale * -1, 0, purpleoverlay, image_alpha);
shader_reset();
draw_self();
