image_xscale = 1.1;
image_yscale = 1.1;
randomize();
random_index = irandom_range(0, 4);
image_index = random_index;
scale = 1.1;
curvelinear = animcurve_get_channel(Curve, "acLinear");
curveease = animcurve_get_channel(Curve, "acEase");
curveslower = animcurve_get_channel(Curve, "acSlower");
curvefaster = animcurve_get_channel(Curve, "acFaster");
percent1 = 0;
uniTime = shader_get_uniform(shader_Distort, "time");
uniTexel = shader_get_uniform(shader_Distort, "texel");
