image_speed = 0;
curvelinear = animcurve_get_channel(Curve, "acLinear");
curveease = animcurve_get_channel(Curve, "acEase");
curveslower = animcurve_get_channel(Curve, "acSlower");
curvefaster = animcurve_get_channel(Curve, "acFaster");
percent1 = 0;
percent2 = 0;
percent3 = 0;
percent4 = 0;
percent5 = 0;
timer = -1;
d16timer = -1;
d16endtimer = -1;
d20trigger = false;
d20timer = -1;
blackalpha = 1;
audio_sound_pitch(mus_menacing_rise, 1);
audio_sound_gain(mus_menacing_rise, 0, 0);
audio_sound_pitch(mus_church_knight, 1);
audio_sound_gain(mus_church_knight, 1, 0);
audio_play_sound(mus_church_knight, 1, true);
triggerout = false;
triggertimer = -1;
interacttimer = -2;
talking = false;
subimg = 0;
dialogueicon = 1;
dialogueiconchoice = spr_empty;
quipicon = 0;
dialoguequipchoice = spr_empty;
current_dialogue = "";
displayed_text = "";
letter_index = 0;
sound_playing = false;
text_complete = false;
pause_for_punctuation = false;
pause_for_ellipsis = false;
destroy = false;
typing_speed = 1;
typing_timer = 0;
susietalk = false;
ralseitalk = false;
tennatalk = false;
miketalk = false;
texttalk = false;
cloaktalk = false;
dialoguebottom = true;
dialoguetop = false;
charactertalking = false;
dialogue = 1;
blockprogress = false;
skiptext = false;
skiptimer = 0;
quip = false;
quiplinear = animcurve_get_channel(Curve, "acLinear");
quipindex = 0;
quipx = 310;
quipxoffset = 50;
quipyoffset = 0;
quippercent = 0;
quipalpha = 0;
quipstring = "";
quipicon = spr_empty;
sprite_prefetch(spr_cloak_slash);
sprite_prefetch(spr_SOUL_line);
sprite_prefetch(spr_SOUL);
sprite_prefetch(spr_kris_scare);
sprite_prefetch(spr_kris_scare_slam);
sprite_prefetch(spr_kris_scare_loop);
sprite_prefetch(spr_ralsei_shock);
sprite_prefetch(sKrisWalkRight);
sprite_prefetch(sRalseiWalkLeftUpset);
sprite_prefetch(spr_ralseiroom_end);
flashalpha = 0.4;
flashcolor = 3481108;
