curve1 = animcurve_get_channel(Linear, "acLinear");
percent1 = 0;
out = 0;
angleoffset = 0;
randomize();
holeoffset = 0;
anglecounter = 40;
hole_count = 0;
hit = false;
pull = 1;
purplecolor = 14235093;
SOUL = obj_SOUL_battle_sof;
TP = obj_SOUL_TP_sof;
tphit = false;
tptimer = 0;
multiplier = 1;
