window_set_caption("LAMBDARUNE Chapter 3");
sprite_prefetch(sKrisWalkUp);
sprite_prefetch(sKrisWalkDown);
sprite_prefetch(sKrisWalkLeft);
sprite_prefetch(sKrisWalkRight);
sprite_prefetch(sSusieWalkUp);
sprite_prefetch(sSusieWalkDown);
sprite_prefetch(sSusieWalkLeft);
sprite_prefetch(sSusieWalkRight);
sprite_prefetch(sSusieWalkDownUpset);
sprite_prefetch(sSusieWalkLeftUpset);
sprite_prefetch(sSusieWalkRightUpset);
sprite_prefetch(sRalseiWalkDownUpset);
sprite_prefetch(sRalseiWalkLeftUpset);
sprite_prefetch(sRalseiWalkRightUpset);
sprite_prefetch(spr_explosion);
sprite_prefetch(spr_tenna);
sprite_prefetch(spr_tenna_down);
sprite_prefetch(spr_tenna_land);
sprite_prefetch(spr_tenna_neutral);
sprite_prefetch(spr_tenna_remote);
sprite_prefetch(spr_tenna_roll);
sprite_prefetch(spr_tenna_static);
sprite_prefetch(spr_tenna_wary);
sprite_prefetch(spr_mike_fall);
sprite_prefetch(spr_mike_happiest);
sprite_prefetch(spr_mike_happy);
sprite_prefetch(spr_mike_land);
sprite_prefetch(spr_mike_land_alt);
sprite_prefetch(spr_mike_poo);
sprite_prefetch(spr_mike_spin);
sprite_prefetch(spr_mike_static);
sprite_prefetch(spr_mike_stunned);
sprite_prefetch(sDialogueBox);
sprite_prefetch(spr_kris_fight);
sprite_prefetch(spr_kris_battlemenu);
sprite_prefetch(spr_battlemenu);
sprite_prefetch(spr_battle_blankmenu);
sprite_prefetch(spr_opacitybar_beginning);
sprite_prefetch(spr_opacitybar);
sprite_prefetch(spr_SOUL_jumpout);
sprite_prefetch(spr_bulletboard);
sprite_prefetch(spr_SOUL);
sprite_prefetch(spr_SOUL_battle);
sprite_prefetch(spr_SOUL_TP);
sprite_prefetch(spr_SOUL_TP_yellow);
sprite_prefetch(spr_SOUL_TP_purple);
sprite_prefetch(spr_rudebuster_impact);
sprite_prefetch(spr_attackseparators);
sprite_prefetch(spr_krismenu_attack);
sprite_prefetch(spr_susiemenu_attack);
sprite_prefetch(spr_ralseimenu_attack);
sprite_prefetch(spr_kris_idle);
sprite_prefetch(spr_susie_idle);
sprite_prefetch(spr_ralsei_idle);
sprite_prefetch(spr_krishit);
sprite_prefetch(spr_susiehit);
sprite_prefetch(spr_ralseihit);
sprite_prefetch(spr_ralsei_magic);
sprite_prefetch(spr_c3_dialoguebubble);
sprite_prefetch(spr_maximike);
sprite_prefetch(spr_maximike_channel);
sprite_prefetch(spr_maximike_background_test);
sprite_prefetch(spr_maximike_background);
sprite_prefetch(spr_maximike_foreground_lace);
sprite_prefetch(spr_maximike_mute);
sprite_prefetch(spr_mike_poo);
sprite_prefetch(spr_mike_land);
sprite_prefetch(spr_tenna_roll);
sprite_prefetch(spr_tenna_land);
sprite_prefetch(spr_target);
sprite_prefetch(spr_staticfull);
sprite_prefetch(spr_generator_sio);
sprite_prefetch(spr_revolver);
sprite_prefetch(spr_revolver_bullet);
sprite_prefetch(spr_bomb);
sprite_prefetch(spr_bombpillars);
sprite_prefetch(spr_bomb_blast);
sprite_prefetch(spr_bomb_plus_blast);
sprite_prefetch(spr_bomb_invert);
sprite_prefetch(spr_foanetv_enter);
sprite_prefetch(spr_foanetv_feighline);
sprite_prefetch(spr_foanetv_foane);
sprite_prefetch(spr_foanetv_l);
sprite_prefetch(spr_foanetv_lblack);
sprite_prefetch(spr_foanetv_lstatic);
sprite_prefetch(spr_foanetv_lwhite);
sprite_prefetch(spr_foanetv_static);
sprite_prefetch(spr_fountainx);
sprite_prefetch(spr_fountainx_small);
sprite_prefetch(spr_bomb);
sprite_prefetch(spr_bomb_blast);
sprite_prefetch(spr_bomb_invert);
sprite_prefetch(spr_bomb_plus);
sprite_prefetch(spr_bomb_plus_blast);
sprite_prefetch(spr_bomb_plus_invert);
sprite_prefetch(spr_bombpillars);
sprite_prefetch(spr_bombpillars_edit);
sprite_prefetch(spr_ch3_fakecredits);
sprite_prefetch(spr_cloud_sio);
sprite_prefetch(spr_elec_sio);
sprite_prefetch(spr_elec_sio_hit);
sprite_prefetch(spr_generator_sio);
sprite_prefetch(spr_maximike);
sprite_prefetch(spr_maximike_background);
sprite_prefetch(spr_maximike_background_new);
sprite_prefetch(spr_maximike_background_test);
sprite_prefetch(spr_maximike_channel);
sprite_prefetch(spr_maximike_dbz);
sprite_prefetch(spr_maximike_foreground_lace);
sprite_prefetch(spr_maximike_horizon);
sprite_prefetch(spr_maximike_hurt);
sprite_prefetch(spr_maximike_mute);
sprite_prefetch(spr_maximike_off);
sprite_prefetch(spr_maximike_screen);
sprite_prefetch(spr_maximike_tennaeject);
sprite_prefetch(spr_middlespikes);
sprite_prefetch(spr_mike_fall);
sprite_prefetch(spr_mike_happiest);
sprite_prefetch(spr_mike_happy);
sprite_prefetch(spr_mike_land);
sprite_prefetch(spr_mike_land_alt);
sprite_prefetch(spr_mike_poo);
sprite_prefetch(spr_mike_spin);
sprite_prefetch(spr_mike_spin_old);
sprite_prefetch(spr_mike_spin_rollerblades);
sprite_prefetch(spr_mike_stand);
sprite_prefetch(spr_mike_static);
sprite_prefetch(spr_mike_stunned);
sprite_prefetch(spr_minitv);
sprite_prefetch(spr_nanomike);
sprite_prefetch(spr_nanomike_jig);
sprite_prefetch(spr_pylon);
sprite_prefetch(spr_rain_sio);
sprite_prefetch(spr_rain_sio_blue);
sprite_prefetch(spr_remote_fall);
sprite_prefetch(spr_remote_spin);
sprite_prefetch(spr_revolver);
sprite_prefetch(spr_revolver_bullet);
sprite_prefetch(spr_sio_clouds);
sprite_prefetch(spr_sio_pathout);
sprite_prefetch(spr_sio_screenshow_1);
sprite_prefetch(spr_sio_screenshow_2);
sprite_prefetch(spr_sio_screenshow_3);
sprite_prefetch(spr_spikebarrier);
sprite_prefetch(spr_spikebarrier_2);
sprite_prefetch(spr_sun);
sprite_prefetch(spr_sunray);
sprite_prefetch(spr_sunray_full);
sprite_prefetch(spr_tenna);
sprite_prefetch(spr_tenna_down);
sprite_prefetch(spr_tenna_land);
sprite_prefetch(spr_tenna_neutral);
sprite_prefetch(spr_tenna_remote);
sprite_prefetch(spr_tenna_roll);
sprite_prefetch(spr_tenna_static);
sprite_prefetch(spr_tenna_wary);
sprite_prefetch(spr_thunder);
sprite_prefetch(spr_thunder_spots);
sprite_prefetch(spr_tv_sio);
sprite_prefetch(spr_tvcable_stretch);
sprite_prefetch(spr_tvcable_stretch_rotate);
sprite_prefetch(spr_z_sleep);
initialtimer = -1;
timer = -1;
global.playermove = false;

if (room == rm_ch3_maximike)
{
    global.battle = false;
}
else if (room == rm_ch3_maximike_skip)
{
    global.battle = true;
    obj_kris_sio.battlestart = true;
    obj_maximike_background.pos_bx = 1000;
}
else if (room == rm_ch3_maximike_prelude)
{
    global.playermove = true;
}

var cam_x = camera_get_view_x(view_camera[0]);
var cam_y = camera_get_view_y(view_camera[0]);

if (global.c3maximikecompleted)
{
    if (room == rm_ch3_maximike_prelude && !instance_exists(obj_sio_specialtrigger))
        instance_create_depth(cam_x + 320, cam_y + 48, -1000, obj_sio_specialtrigger);
}
