curve1 = animcurve_get_channel(Linear, "acLinear");
percent1 = 0;
out = 0;
angleoffset = 0;
randomize();
holeoffset = 0;
anglecounter = 40;
hole_count = 4;
hit = false;
purplecolor = 14235093;
tphit = false;
tptimer = 0;
audio_play_sound(snd_phone, 1, false, 0.66, 0, 0.66);
deleteable = false;
deleteself = false;
