window_set_caption("LAMBDARUNE Chapter 3");
sprite_prefetch(sSusieDialogueSprite);
sprite_prefetch(sDialogueBox);
timer = 0;
dialogue2timer = 0;
dialogue4timer = 0;
dialogue6timer = 0;
dialogue12timer = 0;
dialogue19timer = 0;
global.alldown = false;
global.dialogue = 1;
global.ralseitalk = false;
global.susietalk = false;
global.texttalk = false;
global.emptytalk = false;
global.kreidtalk = false;
global.chairieltalk = false;
global.playermove = false;
global.dialoguetop = false;
global.dialoguebottom = true;
