global.current_dialogue = "";
global.displayed_text = "";
global.letter_index = 0;
global.sound_playing = false;
global.text_complete = false;
global.pause_for_punctuation = false;
global.pause_for_ellipsis = false;
global.typing_speed = 1;
global.typing_timer = 0;
audio_stop_sound(mus_wind);
blockprogress = false;
font = fDeterminationMW;
skiptext = false;
skiptimer = 0;
knighttexttimer = 0;
knightastexttimer = 0;
blocktimer1 = 0;
reset_dialogue();
randomize();
value = irandom_range(1, 2);
d1timer = 0;
d2timer = 0;
d14timer = 0;
d17timer = 0;
d30timer = 0;
d46timer = 0;
d48timer = 0;
d52timer = 0;
