var cam_x = camera_get_view_x(view_camera[0]);
var cam_y = camera_get_view_y(view_camera[0]);
draw_self();
shader_set(sh_wavewarp);
var tex1 = sprite_get_texture(spr_sof_background_end_2, 0);
var uvs1 = sprite_get_uvs(spr_sof_background_end_2, 0);
shader_set_uniform_f(shader_get_uniform(sh_wavewarp, "u_time"), current_time / 1000);
shader_set_uniform_f(shader_get_uniform(sh_wavewarp, "u_amplitude"), 0.001);
shader_set_uniform_f(shader_get_uniform(sh_wavewarp, "u_frequency"), 300 * freqboost);
shader_set_uniform_f(shader_get_uniform(sh_wavewarp, "u_speed"), 0.5);
shader_set_uniform_f(shader_get_uniform(sh_wavewarp, "u_rainbow_speed"), 0);
shader_set_uniform_f(shader_get_uniform(sh_wavewarp, "u_saturation"), 1);
shader_set_uniform_f(shader_get_uniform(sh_wavewarp, "u_uv_top_left"), uvs1[0], uvs1[1]);
shader_set_uniform_f(shader_get_uniform(sh_wavewarp, "u_uv_bottom_right"), uvs1[2], uvs1[3]);
texture_set_stage(0, tex1);
shader_set_uniform_i(shader_get_uniform(sh_wavewarp, "u_texture"), 0);
draw_sprite_ext(spr_sof_background_end_2, 0, 320, 240, 1, 1, 0, c_white, image_alpha);
shader_reset();
draw_sprite_ext(sBlackScreen, 0, 320, 240, 2, 2, 0, c_white, 0.2);
