image_xscale = -2;
image_yscale = 2;
curve1 = animcurve_get_channel(Linear, "acLinear");
percent1 = 0;
curve2 = animcurve_get_channel(Linear, "acLinear");
percent2 = 0;
curve3 = animcurve_get_channel(Linear, "acLinear");
percent3 = 0;
timer = 0;
image_alpha = 0;
audio_play_sound(snd_spare, 1, false);
window_set_caption("LAMBDARUNE Chapter 3");
