curve1 = animcurve_get_channel(Bezier, "acFastToSlow_1");
percent1 = 0;
image_alpha = 0;
depth = -45;
image_xscale = 2;
image_yscale = 2;
xx = x;
yy = y;
randomize();
xoffset = random_range(-50, 50);
yoffset = 0;
