translation_load_all()
global.GameState = new GameStateCreate();
depth = -666;
window_set_caption(translation_get_string("oPersistent_Create_0_0"));
sprite_prefetch(global.sLambdaruneLogo);
audio_sound_gain(snd_stringpull, 0.7, 0);
checkonce = true;
androidsavetimer = 10;
global.afterfirstopen = false;
global.c3cutscenecompleted = false;
global.c3outskirtscompleted = false;
global.c3kreidcompleted = false;
global.c3shadowshopcompleted = false;
global.c3foanecompleted = false;
global.c3kreidfightcompleted = false;
global.c3egg = false;
global.c3primcompleted = false;
global.c3maximikecompleted = false;
global.c3signalcompleted = false;
global.c3epiloguecompleted = false;
global.c3kreidnohit = false;
global.c3maximikenohit = false;
global.c3foanenohit = false;
ini_open("file0.ini");
global.afterfirstopen = ini_read_real("PlayerData", "afterfirstopen", global.afterfirstopen);
global.c3cutscenecompleted = ini_read_real("PlayerData", "c3cutscenecompleted", global.c3cutscenecompleted);
global.c3outskirtscompleted = ini_read_real("PlayerData", "c3outskirtscompleted", global.c3outskirtscompleted);
global.c3kreidcompleted = ini_read_real("PlayerData", "c3kreidcompleted", global.c3kreidcompleted);
global.c3shadowshopcompleted = ini_read_real("PlayerData", "c3shadowshopcompleted", global.c3shadowshopcompleted);
global.c3foanecompleted = ini_read_real("PlayerData", "c3foanecompleted", global.c3foanecompleted);
global.c3kreidfightcompleted = ini_read_real("PlayerData", "c3kreidfightcompleted", global.c3kreidfightcompleted);
global.c3egg = ini_read_real("PlayerData", "c3egg", global.c3egg);
global.c3primcompleted = ini_read_real("PlayerData", "c3primcompleted", global.c3primcompleted);
global.c3maximikecompleted = ini_read_real("PlayerData", "c3maximikecompleted", global.c3maximikecompleted);
global.c3signalcompleted = ini_read_real("PlayerData", "c3signalcompleted", global.c3signalcompleted);
global.c3epiloguecompleted = ini_read_real("PlayerData", "c3epiloguecompleted", global.c3epiloguecompleted);
global.c3kreidnohit = ini_read_real("PlayerData", "c3kreidnohit", global.c3kreidnohit);
global.c3maximikenohit = ini_read_real("PlayerData", "c3maximikenohit", global.c3maximikenohit);
global.c3foanenohit = ini_read_real("PlayerData", "c3foanenohit", global.c3foanenohit);
ini_close();
