window_set_caption(get_lang_string("oGlobalOpeningCinematic_Create_0_0"));
global.timer = 0;
global.cinematicdialogue = 1;
global.shoptalkmenu = false;
global.ralseitalk = false;
global.susietalk = false;
global.texttalk = false;
global.emptytalk = false;
fadeout = false;
blackalpha = 0;
timer = 0;
