window_set_caption(translation_get_string("oGlobalC3Room4_Create_0_0"));
sprite_prefetch(sSusieDialogueSprite);
sprite_prefetch(sDialogueBox);
timer = 0;
dialogue2timer = 0;
dialogue4timer = 0;
dialogue6timer = 0;
dialogue12timer = 0;
dialogue19timer = 0;
global.alldown = false;
global.dialogue = 1;
global.ralseitalk = false;
global.susietalk = false;
global.texttalk = false;
global.emptytalk = false;
global.kreidtalk = false;
global.chairieltalk = false;
global.playermove = true;
global.dialoguetop = false;
global.dialoguebottom = true;
global.cxoffset = 0;
global.cyoffset = 0;
