window_set_caption(get_lang_string("oGlobalC3Room_spacechannel2_Create_0_0"));
audio_sound_gain(snd_foane, 0.4, 0);
audio_sound_gain(snd_mike, 0.6, 0);
audio_play_sound(mus_outofbounds, 1, true);
sprite_prefetch(sSusieDialogueSprite);
sprite_prefetch(sDialogueBox);
timer = 0;
dialogue2timer = 0;
dialogue4timer = 0;
dialogue6timer = 0;
dialogue12timer = 0;
dialogue19timer = 0;
global.dialogue = 1;
global.ralseitalk = false;
global.susietalk = false;
global.texttalk = false;
global.emptytalk = false;
global.foanetalk = false;
global.feighlinetalk = false;
global.missedopportunity = false;
global.playermove = true;
global.charactertalking = false;
global.dialoguetop = false;
global.dialoguebottom = true;
