xx = x;
timer = -1;
randomize();
randomxscale = choose(-1, -0.8, 0.6, 0.8, 1, 1, 1);
randomdirection = choose(-1, 1);
randomspeed = random_range(0.8, 1.2);
sprite_index = spr_string_purple_idle;
image_xscale = 1;
image_alpha = 1;
flashalpha = 0;
flashcolor = 16777215;
flashtrigger = false;
flashpercent = 0;
image_speed = randomspeed;
