window_set_caption(lang("oGlobalC3KreidRoom_Create_0_0"));
sprite_prefetch(sShadowmanIdle);
sprite_prefetch(sKreidDialogueSprite);
sprite_prefetch(spr_shadowman_flying);
sprite_prefetch(spr_shadowman_flying_r);
sprite_prefetch(spr_shadowman_shock);
sprite_prefetch(spr_chairiel);
sprite_prefetch(spr_kreidhatidle);
sprite_prefetch(spr_kreidhatidle2);
sprite_prefetch(spr_kreidhatremove);
sprite_prefetch(spr_kreidhatwalk);
sprite_prefetch(spr_kreidhatunremove);
curve1 = animcurve_get_channel(Linear, "acLinear");
percent1 = 0;
cam_xpre = 0;
timer = 0;
shadowspawn = false;
global.dialogue = 1;
global.ralseitalk = false;
global.kreidtalk = false;
global.susietalk = false;
global.texttalk = false;
global.emptytalk = false;
global.chairieltalk = false;
global.charactertalking = false;
global.playermove = false;
global.dialoguetop = false;
global.dialoguebottom = true;
