draw_set_color(c_black);
draw_sprite_ext(sprite_index, image_index, x + 2, y, image_xscale, image_yscale, 0, c_black, 1);
draw_sprite_ext(sprite_index, image_index, x + 2, y + 2, image_xscale, image_yscale, 0, c_black, 1);
draw_sprite_ext(sprite_index, image_index, x, y + 2, image_xscale, image_yscale, 0, c_black, 1);
draw_sprite_ext(sprite_index, image_index, x - 2, y + 2, image_xscale, image_yscale, 0, c_black, 1);
draw_sprite_ext(sprite_index, image_index, x - 2, y, image_xscale, image_yscale, 0, c_black, 1);
draw_sprite_ext(sprite_index, image_index, x - 2, y - 2, image_xscale, image_yscale, 0, c_black, 1);
draw_sprite_ext(sprite_index, image_index, x, y - 2, image_xscale, image_yscale, 0, c_black, 1);
draw_sprite_ext(sprite_index, image_index, x + 2, y - 2, image_xscale, image_yscale, 0, c_black, 1);
draw_set_color(c_white);
draw_self();
