window_set_caption(lang("oGlobalC3Room2_Create_0_0"));
sprite_prefetch(sSusieDialogueSprite);
sprite_prefetch(sDialogueBox);
timer = 0;
dialogue2timer = 0;
dialogue4timer = 0;
dialogue6timer = 0;
dialogue12timer = 0;
dialogue19timer = 0;
global.geartime = true;
global.savesusie = false;
global.morehungry = false;
global.dialogue = 1;
global.wtfdialogue = 0;
global.ralseitalk = false;
global.susietalk = false;
global.texttalk = false;
global.emptytalk = false;
global.charactertalking = false;
global.susieout = false;
global.playermove = false;
global.dialoguetop = false;
global.dialoguebottom = true;
