var cx = camera_get_view_x(view_camera[0]);
var cy = camera_get_view_y(view_camera[0]);
debug = false;
window_set_caption(get_lang_string("obj_battle_sio_Create_0_0"));
randomize();
instance_create_depth(cx + 320, cy + 240, -666, obj_tpbar);
audio_sound_gain(mus_tennasiblings_boss, 1, 0);
audio_play_sound(mus_tennasiblings_boss, 10, true, 0.9);
global.endofbattle = false;
endtimer = -1;
global.nohit = true;
global.onetap = false;
susiepissed = false;
susiepissturn = 0;
global.krismaxhp = 160;
global.krishp = 160;
global.susiemaxhp = 190;
global.susiehp = 190;
global.ralseimaxhp = 140;
global.ralseihp = 140;
global.enemyhp = 6250;
global.enemymaxhp = 6250;
global.generator1hp = 10;
global.generator2hp = 10;
global.mercy = 0;
global.tp = 0;
global.turn = 1;
global.enemyturn = false;
global.alldown = false;

if (instance_exists(obj_sio_specialtrigger))
{
    obj_sio_specialtrigger.triggered = true;
    
    if (obj_sio_specialtrigger.nohit)
    {
        global.krishp = 1;
        global.krismaxhp = 1;
        global.susiehp = 1;
        global.susiemaxhp = 1;
        global.ralseihp = 1;
        global.ralseimaxhp = 1;
        global.onetap = true;
    }
}

global.topoffset = 0;
global.bottomoffset = 0;
global.leftoffset = 0;
global.rightoffset = 0;
depth = -666;
generaltimer = -1;
textmenu = true;
textenemy = false;
textact = false;
dialogueicon = 1;
iconoffsetx = 0;
textxoffset = -34;
textyoffset = -120;
dialoguebubblexscale = 1;
current_dialogue = "";
displayed_text = "";
letter_index = 0;
sound_playing = false;
text_complete = false;
pause_for_punctuation = false;
pause_for_ellipsis = false;
destroy = false;
typing_speed = 1;
typing_timer = 0;
d57timer = -1;
tennatalk = false;
miketalk = false;
susietalk = false;
ralseitalk = false;
emptytalk = false;
texttalk = true;
dialoguebottom = true;
dialoguetop = false;
charactertalking = false;
menudialogue = 1;
enemydialogue = 1;
enemydialoguecount = 1;
actdialogue = 1;
reason = 0;
randomize();
randomtextjam = irandom_range(0, 2);
jamwait = 0;
susiejaminterrupt = false;
jammer = false;
jammed = false;
generator1 = false;
generator2 = false;
jamphase = 0;
jamdifficulty = -1;
jamtext = "";
tennatext = "";
mercyall = round(8 + (jamphase / 1));
mercyactionadd = round(2 + (jamphase / 1.5));
ACTNAME = get_lang_string("obj_battle_sio_Create_0_1");
blockprogress = false;
skiptext = false;
skiptimer = 0;
curvelinear = animcurve_get_channel(Curve, "acLinear");
curveease = animcurve_get_channel(Curve, "acEase");
curveslower = animcurve_get_channel(Curve, "acSlower");
curvefaster = animcurve_get_channel(Curve, "acFaster");
percentblankrise = 0;
percentdownk = 0;
percentupk = 1;
percentdowns = 1;
percentups = 0;
percentdownr = 1;
percentupr = 0;
inputtimer = -2;
pos_y = cy + 400;
pos_y2 = cy + 430;
pos_ys = cy + 400;
pos_y2s = cy + 430;
pos_yr = cy + 400;
pos_y2r = cy + 430;
kriscolor = 16776960;
susiecolor = 16711935;
ralseicolor = 65280;
menucolor = 3350579;
tpcolor = 4235519;
darkred = 128;
orange = 2117887;
green = 65280;
flashpercent = 0;
flashresettimer = -1;
turnrefresh = false;
turnprogress = false;
susieprogress = false;
ralseiprogress = false;
progressfinal = false;
krisdefending = false;
susiedefending = false;
ralseidefending = false;
ENGINE = self;
ATTACK = obj_attack_sio;
ENEMYNAME = get_lang_string("obj_battle_sio_Create_0_2");
ENEMY1 = obj_maximike_battle;
ENEMYinitialx = obj_maximike_battle.x;
SOUL = obj_SOUL_battle_sio;
PARTYMEMBER1 = obj_kris_sio;
PARTYMEMBER2 = obj_susie_sio;
PARTYMEMBER3 = obj_ralsei_sio;
PAINCHOICE = obj_kris_sio;
PAINHP = global.krishp;
PARTYMEMBER1.sprite_index = spr_kris_idle;
PARTYMEMBER1.image_speed = 1;
PARTYMEMBER2.sprite_index = spr_susie_idle;
PARTYMEMBER2.image_speed = 1;
PARTYMEMBER3.sprite_index = spr_ralsei_idle;
PARTYMEMBER3.image_speed = 1;
krismenux = 107;
susiemenux = 320;
ralseimenux = 533;
krisdown = false;
susiedown = false;
ralseidown = false;
battlebegun = false;
barsubimg = 0;
soulsubimg = -1;
soulsubimgback = -1;
krismenuaccessible = false;
krismenuoptions = 1;
krisbattleicon = 0;
krisselected = false;
krisdefend = false;
krisactselected = false;
krisactoptions = 0;
krisacting = false;
krismercy = false;
krisitem = false;
krisitemtimer = -1;
krisfight = false;
krishurt = false;
susiemenuaccessible = false;
susiemenuoptions = 1;
susiebattleicon = 0;
susieselected = false;
susiedefend = false;
susieactselected = false;
susieactoptions = 0;
susieactoptionsvertical = 0;
susieacting = false;
susiemagic = false;
susiemercy = false;
susieitem = false;
susieitemtimer = -1;
susiefight = false;
susiehurt = false;
ralseimenuaccessible = false;
ralseimenuoptions = 1;
ralseibattleicon = 0;
ralseiselected = false;
ralseidefend = false;
ralseiactselected = false;
ralseiactoptions = 0;
ralseiactoptionsvertical = 0;
ralseiacting = false;
ralseimagic = false;
ralseimagicselected = false;
ralseimercy = false;
ralseiitem = false;
ralseiitemtimer = -1;
ralseifight = false;
ralseihurt = false;
hurttimer = -1;
krisswitch = false;
susieswitch = false;
ralseiswitch = false;
susiedeswitch = false;
ralseideswitch = false;
randompick = irandom_range(1, 5);
used_itemk = 0;
used_items = 0;
used_itemr = 0;
empty = 666;
itemfullname = "";
last_used_indexk = empty;
last_used_indexr = empty;
last_used_indexs = empty;
healmenu = false;
healoption = 0;
itemtargetk = PARTYMEMBER1;
itemtargets = PARTYMEMBER2;
itemtargetr = PARTYMEMBER3;
advancecounter = 0;
itemsection = 0;
itemrows = 0;
itemcolumns = 0;
itemy = cy + 393;
itemx = cx + 18;
global.item_data = ds_map_create();

function define_item(arg0, arg1, arg2, arg3, arg4, arg5)
{
    var entry = ds_map_create();
    ds_map_add(entry, "name", arg1);
    ds_map_add(entry, "short", arg2);
    ds_map_add(entry, "hover", arg3);
    ds_map_add(entry, "heal", arg4);
    ds_map_add(entry, "team_heal", arg5);
    ds_map_add(global.item_data, arg0, entry);
}

ITEM_KREID = 0;
ITEM_DONUT = 1;
ITEM_JUNK = 2;
ITEM_STRUDEL = 3;
ITEM_BTEA = 4;
ITEM_SPINCAKE = 5;
ITEM_TEA = 6;
ITEM_TV = 7;
ITEM_REVIVE = 8;
ITEM_EMPTY = -1;
itemlist = [ITEM_KREID, ITEM_DONUT, ITEM_JUNK, ITEM_REVIVE, ITEM_SPINCAKE, ITEM_KREID, ITEM_KREID, ITEM_REVIVE, ITEM_DONUT, ITEM_TV, ITEM_TV, ITEM_TV];
define_item(ITEM_KREID, get_lang_string("obj_battle_sio_Create_0_3"), get_lang_string("obj_battle_sio_Create_0_4"), get_lang_string("obj_battle_sio_Create_0_5"), 140, false);
define_item(ITEM_DONUT, get_lang_string("obj_battle_sio_Create_0_6"), get_lang_string("obj_battle_sio_Create_0_7"), get_lang_string("obj_battle_sio_Create_0_8"), 70, false);
define_item(ITEM_JUNK, get_lang_string("obj_battle_sio_Create_0_9"), get_lang_string("obj_battle_sio_Create_0_10"), get_lang_string("obj_battle_sio_Create_0_11"), 70, false);
define_item(ITEM_STRUDEL, get_lang_string("obj_battle_sio_Create_0_12"), get_lang_string("obj_battle_sio_Create_0_13"), get_lang_string("obj_battle_sio_Create_0_14"), 90, false);
define_item(ITEM_BTEA, get_lang_string("obj_battle_sio_Create_0_15"), get_lang_string("obj_battle_sio_Create_0_16"), get_lang_string("obj_battle_sio_Create_0_17"), 777, true);
define_item(ITEM_SPINCAKE, get_lang_string("obj_battle_sio_Create_0_18"), get_lang_string("obj_battle_sio_Create_0_19"), get_lang_string("obj_battle_sio_Create_0_20"), 140, true);
define_item(ITEM_TEA, get_lang_string("obj_battle_sio_Create_0_21"), get_lang_string("obj_battle_sio_Create_0_22"), get_lang_string("obj_battle_sio_Create_0_23"), 10, false);
define_item(ITEM_TV, get_lang_string("obj_battle_sio_Create_0_24"), get_lang_string("obj_battle_sio_Create_0_25"), get_lang_string("obj_battle_sio_Create_0_26"), 110, false);
define_item(ITEM_REVIVE, get_lang_string("obj_battle_sio_Create_0_27"), get_lang_string("obj_battle_sio_Create_0_28"), get_lang_string("obj_battle_sio_Create_0_29"), 999, false);
define_item(ITEM_EMPTY, "error", "", "", 0, false);
