window_set_caption(get_lang_string("oGlobalC3Room5_Create_0_0"));
sprite_prefetch(sShadowmanIdle);
sprite_prefetch(sShadowmanIdleWhite);
sprite_prefetch(sSpareStar);
sprite_prefetch(sZ);
timer = 0;
dialogue15timer = 0;
dialogue17timer = 0;
global.dialogue = 1;
global.ralseitalk = false;
global.susietalk = false;
global.texttalk = false;
global.emptytalk = false;
global.demo = true;
instance_destroy(oGlobalHP_R3);
instance_destroy(obj_chaseSR_empty);
instance_destroy(obj_healthbar_kris);
instance_destroy(obj_healthbar_susie);
instance_destroy(txt_krishp_overworld);
instance_destroy(txt_krismaxhp_overworld);
instance_destroy(txt_susiehp_overworld);
instance_destroy(txt_susiemaxhp_overworld);
global.playermove = false;
global.dialoguetop = false;
global.dialoguebottom = true;
