window_set_caption(get_lang_string("oGlobalFalseFountain_Create_0_0"));
sprite_prefetch(sDialogueBox);
sprite_prefetch(spr_foanetv_enter);
sprite_prefetch(spr_foanetv_feighline);
sprite_prefetch(spr_foanetv_enter);
sprite_prefetch(spr_foanetv_foane);
sprite_prefetch(spr_foanetv_l);
sprite_prefetch(spr_foanetv_lblack);
sprite_prefetch(spr_foanetv_lstatic);
sprite_prefetch(spr_foanetv_static);
sprite_prefetch(sSusieShockedFront);
sprite_prefetch(sSusieShockedFront2);
sprite_prefetch(spr_fountainx);
sprite_prefetch(spr_fountainx_small);
depth = -80;
timer = -1;
percentfadeout = 0;
alpha = 1;
curvelinear = animcurve_get_channel(Curve, "acLinear");
curveease = animcurve_get_channel(Curve, "acEase");
curveslower = animcurve_get_channel(Curve, "acSlower");
curvefaster = animcurve_get_channel(Curve, "acFaster");
global.playermove = false;
audio_play_sound(THE_HOLY, 1, true);
