randomize();
randomplus = random_range(1, 1.8);
image_index = irandom_range(0, 3);
image_blend = c_red;
timer = -1;
timer2 = 0;
timer3 = -1;
alpha = 0;
alpha2 = 0;
deletevalue = 0;
image_alpha = alpha + ((sin(timer2 / 4) * 1) / 4);
hit = false;
tptimer = 0;
tptrigger = false;
