image_xscale = 2;
image_yscale = 2;
timer = 0;
blackalpha = 0;
audio_play_sound(snd_battleenter, 1, false, 0.5);
curvelinear = animcurve_get_channel(Curve, "acLinear");
curveease = animcurve_get_channel(Curve, "acEase");
curveslower = animcurve_get_channel(Curve, "acSlower");
curvefaster = animcurve_get_channel(Curve, "acFaster");
percent1 = 0;
percent2 = 0;
