generaltimer = -1;
xx = x;
xoffset = 0;
randomize();
windoffset = 0;
extrawind = random_range(-0.5, 0.5);
image_index = irandom_range(0, 2);
image_xscale = 2;
image_yscale = 2;
angle = image_angle;
angleoffset = 0;
