window_set_caption(lang("oGlobalC3Room6_Create_0_0"));
sprite_prefetch(sSusieDialogueSprite);
sprite_prefetch(sDialogueBox);
timer = -1;
d33timer = -1;
dialogue2timer = 0;
dialogue4timer = 0;
dialogue6timer = 0;
dialogue12timer = 0;
dialogue19timer = 0;
global.dialogue = 1;
global.ralseitalk = false;
global.susietalk = false;
global.texttalk = false;
global.emptytalk = false;
global.kreidtalk = false;
global.chairieltalk = false;
global.elevatortime = false;
global.dooropen = false;
global.playermove = false;
global.dialoguetop = false;
global.dialoguebottom = true;
global.cxoffset = 0;
global.cyoffset = 0;
