ini_open("file0.ini");
ini_write_real("PlayerData", "afterfirstopen", global.afterfirstopen);
ini_write_real("PlayerData", "c3cutscenecompleted", global.c3cutscenecompleted);
ini_write_real("PlayerData", "c3outskirtscompleted", global.c3outskirtscompleted);
ini_write_real("PlayerData", "c3kreidcompleted", global.c3kreidcompleted);
ini_write_real("PlayerData", "c3shadowshopcompleted", global.c3shadowshopcompleted);
ini_write_real("PlayerData", "c3foanecompleted", global.c3foanecompleted);
ini_write_real("PlayerData", "c3kreidfightcompleted", global.c3kreidfightcompleted);
ini_write_real("PlayerData", "c3egg", global.c3egg);
ini_write_real("PlayerData", "c3primcompleted", global.c3primcompleted);
ini_write_real("PlayerData", "c3maximikecompleted", global.c3maximikecompleted);
ini_write_real("PlayerData", "c3signalcompleted", global.c3signalcompleted);
ini_write_real("PlayerData", "c3epiloguecompleted", global.c3epiloguecompleted);
ini_write_real("PlayerData", "c3kreidnohit", global.c3kreidnohit);
ini_write_real("PlayerData", "c3maximikenohit", global.c3maximikenohit);
ini_write_real("PlayerData", "c3foanenohit", global.c3foanenohit);
ini_close();
