timer = -1;
hit = false;
tptimer = 0;
speedx = -2;
randomize();
randomadd = random_range(0, 2/3);
speed = speedx;
image_alpha = 0;
image_speed = 0;
image_index = 0;
curvelinear = animcurve_get_channel(Curve, "acLinear");
curveease = animcurve_get_channel(Curve, "acEase");
curveslower = animcurve_get_channel(Curve, "acSlower");
curvefaster = animcurve_get_channel(Curve, "acFaster");
percent1 = 0;
flashalpha = 0;
flashcolor = 16777215;
flashpercent = 0;
flashtrigger = false;
collided = false;
collisiontimer = -1;
change = false;
changetimer = -1;
changed = false;
randomize();
pitch = random_range(1.13, 0.95);
rotatemultiplier = random_range(1, 1.5);
offset = 0;
