if (!(room == rm_ch3_kreidfight) && !(room == rm_ch3_kreidfight_skip))
    window_set_caption(lang("oGlobalC3RoomKreidFight_Create_0_0"));
else
    window_set_caption(lang("oGlobalC3RoomKreidFight_Create_0_1"));

sprite_prefetch(sDialogueBox);
sprite_prefetch(spr_kris_fight);
sprite_prefetch(spr_kris_battlemenu);
sprite_prefetch(spr_battlemenu);
sprite_prefetch(spr_battle_blankmenu);
sprite_prefetch(spr_opacitybar_beginning);
sprite_prefetch(spr_opacitybar);
sprite_prefetch(spr_krishit);
sprite_prefetch(spr_kris_idle);
sprite_prefetch(spr_kris_menuoptions);
sprite_prefetch(spr_tpbar);
sprite_prefetch(spr_tpbar_red);
sprite_prefetch(spr_tpbar_filler);
sprite_prefetch(spr_bulletboard);
sprite_prefetch(spr_whitebox);
sprite_prefetch(spr_kreid_idle);
sprite_prefetch(spr_kreidbullet);
sprite_prefetch(spr_kreidcircle);
sprite_prefetch(spr_circle_100x100);
sprite_prefetch(spr_circle_200x200);
sprite_prefetch(spr_circle_500x500);
sprite_prefetch(spr_circle_1000x1000);
sprite_prefetch(spr_shadowfire);
sprite_prefetch(spr_shadowwave);
sprite_prefetch(spr_SOUL_jumpout);
sprite_prefetch(spr_cloudline1);
sprite_prefetch(spr_cloudline2);
sprite_prefetch(spr_SOUL_TP);
sprite_prefetch(spr_SOUL_TP_yellow);
sprite_prefetch(spr_SOUL_TP_purple);
sprite_prefetch(spr_SOUL_battle);
sprite_prefetch(spr_kreid_warning);
sprite_prefetch(spr_ch3_theatre);
sprite_prefetch(spr_ch3_theatre_camera);
sprite_prefetch(spr_ch3_theatre_display);
sprite_prefetch(spr_ch3_theatre_glow);
sprite_prefetch(spr_ch3_theatre_platform);
sprite_prefetch(spr_eggroom_theatre_tiles);
sprite_prefetch(spr_eggroom_tiles);
sprite_prefetch(spr_neoruins_background);
sprite_prefetch(spr_neoruins_bump);
sprite_prefetch(spr_neoruins_cacti);
sprite_prefetch(spr_neoruins_cacti_1);
sprite_prefetch(spr_neoruins_hill);
sprite_prefetch(spr_neoruins_houses);
sprite_prefetch(spr_neoruins_stone);
sprite_prefetch(spr_hair_kreidaftermath);
sprite_prefetch(spr_kreid_drop);
sprite_prefetch(spr_kreid_kreidaftermath);
sprite_prefetch(spr_kris_kreidaftermath);
sprite_prefetch(IMAGE_OUTLAW_WARNING);
sprite_prefetch(spr_angrytunes);
sprite_prefetch(spr_c3_sky);
sprite_prefetch(spr_ch3_boundary);
sprite_prefetch(spr_ch3_chair);
sprite_prefetch(spr_ch3_chairarm);
sprite_prefetch(spr_ch3_plane_exterior);
sprite_prefetch(spr_ch3_plane_interior);
sprite_prefetch(spr_circle_1000x1000);
sprite_prefetch(spr_circle_100x100);
sprite_prefetch(spr_circle_200x200);
sprite_prefetch(spr_circle_500x500);
sprite_prefetch(spr_clouddepth);
sprite_prefetch(spr_cloudline1);
sprite_prefetch(spr_cloudline2);
sprite_prefetch(spr_crosshair);
sprite_prefetch(spr_crosshair_wide);
sprite_prefetch(spr_egg_c3);
sprite_prefetch(spr_fedorabat);
sprite_prefetch(spr_fire);
sprite_prefetch(spr_kreid_angryleft);
sprite_prefetch(spr_kreid_angryshove);
sprite_prefetch(spr_kreid_bullet);
sprite_prefetch(spr_kreid_cape);
sprite_prefetch(spr_kreid_cape_rage);
sprite_prefetch(spr_kreid_hug);
sprite_prefetch(spr_kreid_hurt);
sprite_prefetch(spr_kreid_idle);
sprite_prefetch(spr_kreid_jump);
sprite_prefetch(spr_kreid_jump_idle);
sprite_prefetch(spr_kreid_jump_placeholder);
sprite_prefetch(spr_kreid_land);
sprite_prefetch(spr_kreid_leftidle);
sprite_prefetch(spr_kreid_nohitnoogie);
sprite_prefetch(spr_kreid_ominous);
sprite_prefetch(spr_kreid_peanuts);
sprite_prefetch(spr_kreid_peanutthrow);
sprite_prefetch(spr_kreid_rage);
sprite_prefetch(spr_kreid_rageleft);
sprite_prefetch(spr_kreid_rolleft);
sprite_prefetch(spr_kreid_slam);
sprite_prefetch(spr_kreid_slam_flash);
sprite_prefetch(spr_kreid_walkdown);
sprite_prefetch(spr_kreid_walkleft);
sprite_prefetch(spr_kreid_walkright);
sprite_prefetch(spr_kreid_walkup);
sprite_prefetch(spr_kreidbullet);
sprite_prefetch(spr_kreidcircle);
sprite_prefetch(spr_kreidelec);
sprite_prefetch(spr_kreidhorns);
sprite_prefetch(spr_kreidknife_1);
sprite_prefetch(spr_kreidknife_2);
sprite_prefetch(spr_kreidmoon);
sprite_prefetch(spr_kris_kreidjump);
sprite_prefetch(spr_krissit);
sprite_prefetch(spr_peanuts);
sprite_prefetch(spr_plane_outside);
sprite_prefetch(spr_planegate);
sprite_prefetch(spr_planegate_barrier);
sprite_prefetch(spr_planegate_door);
sprite_prefetch(spr_planegate_room);
sprite_prefetch(spr_planegate_vase);
sprite_prefetch(spr_ralseisit);
sprite_prefetch(spr_rubble_tower);
sprite_prefetch(spr_shadowblob);
sprite_prefetch(spr_shadowfire);
sprite_prefetch(spr_shadowgun_kreid);
sprite_prefetch(spr_shadowman);
sprite_prefetch(spr_shadowman_sit);
sprite_prefetch(spr_shadowspike);
sprite_prefetch(spr_shadowwave);
sprite_prefetch(spr_susiesit);
sprite_prefetch(spr_tower_1);
sprite_prefetch(spr_tower_2);
sprite_prefetch(spr_tv_collision);
sprite_prefetch(spr_v);
sprite_prefetch(spr_v_aware);
sprite_prefetch(spr_v_aware_leftarm);
sprite_prefetch(spr_v_aware_rightarm);
sprite_prefetch(spr_v_aware_talking);
sprite_prefetch(spr_whitebox);
sprite_prefetch(spr_whitebox_2);
initialtimer = -1;
timer = -1;
global.alldown = false;
gameovertimer = -1;
global.endofbattle = false;
cloudfinal = false;
global.playermove = false;

if (room == rm_ch3_kreidfight)
    global.battle = false;
else
    global.battle = true;

if (!(room == rm_ch3_debug))
{
    audio_sound_gain(mus_wind, 1, 0);
    audio_play_sound(mus_wind, 1, true);
    audio_sound_pitch(mus_wind, 1.1);
}

if (room == rm_ch3_debug)
{
    global.tp = 0;
    global.enemyturn = false;
    global.yoffset = 0;
}
